### ISSUE TITLE
上传图片时,获取不到文件

### ISSUE THREAD

**Issue by yuesf** [wangfupeng1988/wangEditor#497]
上传图片时,获取不到文件, 在解码请求报错.
 List fileItems = sfu.parseRequest(request); // 解码请求
org.apache.commons.fileupload.FileUploadBase$InvalidContentTypeException: the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is null
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:947)
	at org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:310)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:334)
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:115)

**Comment by godcheese** [comment]
大佬我也遇到了您这样的问题，求教如何解决的。
