### ISSUE TITLE
在vue的nuxt环境中，如果在路由中使用编辑器，直接访问路由地址会报错

### ISSUE THREAD

**Issue by foooooouny** [wangfupeng1988/wangEditor#978]
> 在vue的nuxt环境中，如果在路由中使用编辑器，直接访问路由地址会报错，但是如果从另外的路由跳转过去，就不会出问题
报错信息：

```js
ReferenceError: navigator is not defined
    at /Users/zzboy/myFile/task/cpcPackage/founy-vue-nuxt/node_modules/wangeditor/release/wangEditor.js:607:10
    at /Users/zzboy/myFile/task/cpcPackage/founy-vue-nuxt/node_modules/wangeditor/release/wangEditor.js:2:82
    at Object.<anonymous> (/Users/zzboy/myFile/task/cpcPackage/founy-vue-nuxt/node_modules/wangeditor/release/wangEditor.js:5:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at r (/Users/zzboy/myFile/task/cpcPackage/founy-vue-nuxt/node_modules/vue-server-renderer/build.js:7739:16)
    at Object.<anonymous> (server-bundle.js:3120:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.103 (2.nuxt.bundle.649ab762bbbe32a3a2ba.js:40:69)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.78 (2.nuxt.bundle.649ab762bbbe32a3a2ba.js:105:419)
```

**github的demo地址：** `git@github.com:foooooouny/founy-vue-nuxt.git`
启动之后的访问路径：/wangeditor
如果从首页点击跳转链接进去，是没问题的，这个具体是什么问题？

**Comment by foooooouny** [comment]
问题就是由于nuxt 的ssr问题，运行在了服务端，找不到参数。
目前暂时的解决方案，只有将包挂载到vue原型上面，之后希望会有改善：
配置如下：
```js
// nuxt.config.js
plugins: [
  {
      src: '~/plugins/wangeditor', ssr: false
   }
]

// plugins/wangeditor
import Vue from 'vue'
import WangEditor from 'wangeditor'
Object.defineProperty(Vue.prototype, '$wangEditor', { value: WangEditor }


// pages/wangeditor.vue
let Editor = this.$wangEditor
let editor = new Editor('#myEditor')
editor.customConfig.onchange = (html) => {
   this.editorContent = html
}
editor.create()
```

**Comment by wangfupeng1988** [comment]
编辑器还不支持 ssr，代码执行时需要 window 和 document 对象才行。

再者，编辑器也没必要使用 ssr

**Comment by sofichael** [comment]
@foooooouny  按照你的写法，还是会有这样的错误，请问你是如何解决的？
wangEditor.js:4313 Uncaught TypeError: Cannot set property 'id' of null
    at Editor (wangEditor.js:4313)

**Comment by foooooouny** [comment]
@sofichael 后面又出了一些问题，就换用quill了。

**Comment by loveyunk** [comment]
`const E = process.browser ? require('wangeditor') : undefined;`
